server:
  port: 8080

spring:
  application:
    name: mcp-server-test
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        type: sync
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message